### ISSUE TITLE
Move Volunteer and FAQ navbar links into a submenu

### ISSUE THREAD

**Issue by AlphaSheep** [CubingZA/CubingZA-Website#345]
Make a submenu for about and move the volunteer and FAQ and About under that submenu.

This needs to be added along with the rest of the changes in PR #341 

_Originally posted by @AlphaSheep in https://github.com/CubingZA/CubingZA-Website/pull/341#discussion_r1721041883_

**Comment by elfishhenry** [comment]
Doing this was simpler than I thought, I know you've assigned yourself, but I'll commit anyway.

**Comment by elfishhenry** [comment]
@AlphaSheep You should close this
