### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by AlphaSheep** [CubingZA/CubingZA-Website#38]
Create a frequently asked questions section that addresses common questions about speed cubing and the organization.

**Comment by elfishhenry** [comment]
Alright, I'll make a basic page for this, but when the time comes and when you see this, either you can add the FAQS or ask me to, once I've sent the draft of course.

**Comment by elfishhenry** [comment]
Added faqs to my current pr. #341

**Comment by elfishhenry** [comment]
This is what I've made: 
![image](https://github.com/user-attachments/assets/32c69383-a0b4-4683-bd10-3b44151fb659)

**Comment by elfishhenry** [comment]
@AlphaSheep I'd ask for some faqs so that I can add them to the page.
