### ISSUE TITLE
Volunteer opportunities page

### ISSUE THREAD

**Issue by AlphaSheep** [CubingZA/CubingZA-Website#40]
Create a page that highlights volunteer opportunities for the organization and provides information on how to get involved.

**Comment by elfishhenry** [comment]
I've made a simple page (/volunteer), which I've put the navbar next to contact; I didn't quite know if this was what you wanted, but it's something to build off of, let me know what I should add or improve on. 

I've put "example" where the positions should go, but I'm guessing it's the standard running, judging and scrambling.

Sending a pull request.

**Comment by elfishhenry** [comment]
#341 pr.

**Comment by elfishhenry** [comment]
I've re-read the issue and I'm going to add pretty much what you sent in the gmail to me.

**Comment by elfishhenry** [comment]
This is what I've added:

![image](https://github.com/user-attachments/assets/2695a559-ec44-4708-acfe-1e9fbc88f8ec)

**Comment by AlphaSheep** [comment]
Fixed by #341
